### ISSUE TITLE
[Feature Request] Where are the Svelte components?

### ISSUE THREAD

**Issue by Signum** [creativetimofficial/tailwind-webapp-svelte#26]
### What is your enhancement?
Bear with me. I'm new to the Svelte world. So I may be fundamentally wrong.

Looking at Svelte I believe that the greatest gift is adding and using Svelte components. So a UI toolkit would provide lots of components. Somehow I had expected to find a Notus Svelte "<Alert … />" component. However instead I just find the generic code to create an alert (https://www.creative-tim.com/learning-lab/tailwind/svelte/alerts/notus.

Notus Svelte looks gorgeous. But I wouldn't want to create all the Svelte components myself. At it's called Notus SVELTE I'm pretty sure I'm missing the part that lets me use the pretty bits with Svelte.

**Comment by maxmarkus** [comment]
Hi @Signum, I guess what the "misunderstanding" is, that Notus is not a Library that provides a well curated components, but a template that is using tailwind and svelte (and also provides some code snippets) to create the UI.
Building and maintaining library would be much much more work compared to stitching markup with tailwindcss and enrichting it with svelte. I think the Notus maintainer's focus was on the ux and providing a nice template ouf of the box.

And you are right, the Svelte lifting needs to be done by yourself.

It seems to be a nice starting point for your own adventures, yet unmaintained.

**Comment by Signum** [comment]
Thanks, @maxmarkus, for the explanation.
